build.sbt, src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, src/main/scala/net/manub/embeddedkafka/marshalling/avro/marshallers.scala, src/main/scala/net/manub/embeddedkafka/marshalling/avro/package.scala, src/main/scala/net/manub/embeddedkafka/marshalling/marshalling.scala, src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaSpec.scala, src/test/scala/net/manub/embeddedkafka/TestAvroClass.scala
Some refactoring to support:
- Definition of publisher using just the class type (and using implicits)
- Type-specific publish and receive methods
- AVRO support
=> Implicit-based typing and AVRO support

src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, src/main/scala/net/manub/embeddedkafka/EmbeddedKafkaConfig.scala, src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaSpec.scala
Cleaned up the formatting noise and implemented the suggested changes. This PR adds support for custom topic and broker creation by enabling clients to pass a custom config when they create a broker or a topic.
=> Added a way to create topics and brokers by passing a custom configuration

src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala
fixes https://github.com/manub/scalatest-embedded-kafka/issues/16 
It is tested.
=> ZkUtils must be closed after using

README.md
And testing if travis integration for PRs works.
=> Added travis build badge.

README.md, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala
When you use embedded kafka, you may be want to change default properties e.g. you have integration tests and want to start embedded kafka with integration tests in one network node, but an application starts in another network node. Embedded kafka runs with binding to localhost so you cannot to connect to it from another node. This PR fix this problem and you can change default propeties, so now you can set `host.name` and `advertised.host.name` correctly.
=> Cannot change default embedded kafka properties

README.md
This information is not true, after switching to 0.10.1.0 this dependency cannot be manually overridden.
=> Remove information on backward binary compatibility

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala
This could be somehow related to #57.
=> Clear log directories on EmbeddedKafka.stop() or end of withRunningKafka method.

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala
Similar issue in KAFKA
Reference 1: https://issues.apache.org/jira/browse/KAFKA-1881
Reference 2: https://reviews.apache.org/r/31447/diff/1/
Ref #57
=> fix OutOfMemory issue by making the log cleaner dedupe buffer much smaller

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafkaConfig.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
In older versions of scalatest-embedded-kafka you were able to call
consumeFirstStringMessageFrom multiple times, with each invocation
causing the next message in a topic to be consumed. In the latest
version this is no longer the case: the first invocation works fine, but
subsequent invocations would result in exceptions as the first
invocation would cause *all* messages to be committed even though only
the first one is returned. We fix this by disabling auto-commit and
simply committing only the message that consumeFirstStringMessageFrom
returns.
=> Allow consumeFirstStringMessageFrom to be called multiple times

README.md, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafkaConfig.scala
@alexadriaanse I think this leaks less into the Config. Let me know what you think.
=> Refactored autoCommit for consumeFirstMessage methods.

build.sbt
Kafka for Scala 2.12 is now published on Maven Central so this is not needed anymore.
=> Removed Apache Staging from resolvers.

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
Addressing issue #66 with this commit. Also added appropriate test coverage. Please take a look
=> Add batch consumption of messages

README.md, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafkaConfig.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaCustomConfigSpec.scala
Hi
We need to test message flow with messages bigger than default 1MB.
I've prepared a pull request with additional custom producer and consumer configurations.
I also created a unit test for it and updated README with code example.
Can you take a look ?
Any comments welcome
In near future, I plan to merge it to 0.8 branch, because we need it on Spark 1.6
Regards
=> Custom configuration for consumer and producer

build.sbt, embedded-kafka/src/main/scala/net/manub/embeddedkafka/ConsumerExtensions.scala, embedded-kafka/src/test/java/net/manub/embeddedkafka/ConsumerOpsSpec.scala, embedded-kafka/src/test/java/net/manub/embeddedkafka/ConsumerOpsTest.scala
=> Updated to allow passing in maximum number of attempts and poll timeout

README.md, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaWithRunningKafkaOnFoundPortSpec.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/embeddedKafkaSpecSupport.scala
This implements `withRunningKafkaOnFoundPort`, which allows users to run zookeeper/kafka on arbitrary available ports instead of having to hard-code specific ports. This is useful to make tests more reliable, especially when running tests in parallel or on machines where other tests or services may be running with port numbers you can't control.
I'm happy to refactor this however you like. It might be cleaner to just change the implementation of `withRunningKafka` to take `body: EmbeddedKafkaConfig => T` instead of `body: => T`, since that only requires a single implementation. But that breaks backwards compatibility, so I didn't go that direction for now.
=> Implement withRunningKafkaOnFoundPort

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
This simplifies a bit of code, and makes two bigger changes:
1. Implement `consumeNumberMessagesFromTopics`, which reads from multiple topics.
2. Add custom timeout in `consumeNumberMessagesFromTopics`, instead of hard-coding 5 seconds. This also counts the total consume time toward the timeout, rather than timing out if there is a 5 second period of silence. E.g. if a user calls this method with number=12 and timeout=5.seconds, and a producer produces one message every 4 seconds, the method will now throw TimeoutException after 5 seconds. The previous behavior would receive all messages in 60 seconds and not throw an exception, because there was at least one message to consume every 5 seconds.
Since change 2 is an actual behavior change, I can take it out of this PR if backwards …
=> Consume messages with multiple topics and custom timeout

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
This adds support for reading messages with their key, thus returning tuples (key, value).
To preserve the API, I added methods named `consume...KeyedMessages...`. Methods without `Keyed` in their name just return a value, as before.
=> Add support for keyed messages

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
It is very expensive to create a `KafkaProducer`.
For tests that send a lot of messages it is very slow
to use the original `publishToKafka` method that created
a new `KafkaProducer` for each message to send.
Now there is a batch version of `publishToKafka` that
accepts a sequence of key/value tuples and sends them
all with the same `KafkaProducer` instance.
=> Add a batch version of publishToKafka

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafkaConfig.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaWithRunningKafkaOnFoundPortSpec.scala
I'm using Kafka and a schema registry to serialize messages.
I've made a trait that allow me to run a Kafka and a schema registry:
```scala
trait EmbeddedKafkaAndSchemaRegistrySupport extends EmbeddedKafka {
this: Suite =>
def withRunningKafkaAndSchemaRegistry[T](block: (ConfluentConfig) => T): T = {
implicit val kafkaConfig: EmbeddedKafkaConfig = new EmbeddedKafkaConfig(zooKeeperPort = getEphemeralPort, kafkaPort = getEphemeralPort)
EmbeddedKafka.start()
try {
val confluentConfig = ConfluentConfig(kafkaConfig, schemaRegistryPort = getEphemeralPort)
val schemaRegistry = startSchemaRegistry(confluentConfig)
try {
block(confluentConfig)
} finally {
schemaRegistry.stop()
}
} finally {
EmbeddedKafka.stop()
}
}
}
case class ConfluentConfig(embeddedKafkaConfig: EmbeddedKafkaConfig, …
```
=> Make EmbeddedKafkaConfig a trait to allow other implementation

kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreams.scala
pull request for issue #68
use the extraConfig in `net.manub.embeddedkafka.streams.TestStreamsConfig#streamConfig` to allow KafkaStreams confing overriding.
=> Add possibility to override streams config in runStreams method (issue #68)

README.md, embedded-kafka/src/main/scala/net/manub/embeddedkafka/Codecs.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/ConsumerExtensions.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/ConsumerExtensionsSpec.scala, kafka-streams/src/test/scala/net/manub/embeddedkafka/streams/ExampleKafkaStreamsSpec.scala
Addition of a `ConsumerRetryConfig` object for providing the number of attempts and poll duration implicitly when calling `consumeLazily`.
Some refactoring to allow one or many topics to be provided to `consumeLazily` instead of separate methods.
Allow a transform function to be passed to `consumeLazily` to be run on all `ConsumerRecord`s consumed - allows users to decode a `ConsumerRecord` however they want (e.g. I've had times where I need to return the timestamp from a `ConsumerRecord`). This also means we can cover the use-case of the `consumeLazilyOnTopics` method which was extracting the topic from the `ConsumerRecord`. 
I have provided some implementations of this function in `Codecs` which I believe to be common usages.
=> increase flexibility of ConsumerOps

README.md
A miniscule fix to potentially avoid a few seconds of confusion when reading the docs...
(Thanks for a very nice library by the way!)
=> Fix typo in name of Consumers trait

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
=> Method to publish a ProducerRecord

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedServer.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaObjectSpec.scala
```
THIS IS A WORK IN PROGRESS
```
Functionally the changes are made. I would like to make some refactorings first and also look into the query raised by @shashidesai.
I'm raising this PR now in the hopes that you can take a look at my approach. If you have any major concerns it would be best to find out sooner!
Closes #101 
TODO:
Running tests in parallel which use `EmbeddedKafka` can run into an issue with the log files as `EmbeddedKafka#stop` clears all temporary log directories, which another instance of kafka may still be relying on in another test.
To see this error I changed `logback.xml` line 1 to: `log4j.rootLogger=error,stdout`:
`FATAL [Replica Manager on Broker 0]: Error writing to highwatermark file` ... `java.io.FileNotFoundException` ... …
=> Concurrent kafka instances

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala
I have found that the `topic` argument have never been used in the `publishToKafka(ProducerRecord)` method. This is expected, because the `topic` is available in the `ProducerRecord`.
=> Simplify publish producer record method - remove unused topic argument

README.md
Scala examples in `README.md` are not working out-of-the-box.
Also the Streams examples is missing an import statement and an explicit type.
=> fix README.md Scala examples

kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreams.scala
`=> Any` is not a very good looking return type.
=> Make runStreams return value comply with withRunningKafka's

build.sbt, embedded-kafka/src/main/scala/net/manub/embeddedkafka/ConsumerExtensions.scala, kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreams.scala
Why exclude `slf4j-log4j12` and moments later reimport it?
Also remove the few usages of `Logger` since they're not providing any real value.
=> Fix logging dependencies

embedded-kafka/src/main/scala/net/manub/embeddedkafka/Consumers.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaCustomConfigSpec.scala, kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/TestStreamsConfig.scala
Fix #118.
Java `Properties` are still used when creating Schema Registry instances and topics via `AdminUtils` (#121 will take care of the latter).
=> Use Scala Map instead of Java Properties, when possible

embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedServer.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaObjectSpec.scala
instance.  Previously, if 0 was passed for both kafka and zookeeper
ports, zookeeper would start on an available port; however, kafka was
told that zookeeper was listening on port 0.
Addresses #143 
I also removed the implicit config from `EmbeddedK`.  It didn't look
like it was being used anywhere...  However, I added it as a required
argument.  This was done to allow Java code like this:
```java
int kafkaPort = 0;
int zookeeperPort = 0;
EmbeddedKafka$ kafka = EmbeddedKafka$.MODULE$;
EmbeddedKafkaConfig cfg = new EmbeddedKafkaConfigImpl(
kafkaPort,
zookeeperPort,
Map$.MODULE$.empty(),
Map$.MODULE$.empty(),
Map$.MODULE$.empty()
);
EmbeddedK serverInfo = kafka.start(cfg);
EmbeddedKafkaConfig actualCfg = serverInfo.config();
kafka.publishStringMessageToKafka("topic", "message", actualCfg); …
```
=> 143 Kafka should be configured to point to the launched zookeeper

build.sbt, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreams.scala, kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreamsAllInOne.scala, schema-registry/src/main/scala/net.manub.embeddedkafka/schemaregistry/streams/EmbeddedKafkaStreamsWithSchemaRegistry.scala, schema-registry/src/main/scala/net.manub.embeddedkafka/schemaregistry/streams/EmbeddedKafkaStreamsWithSchemaRegistryAllInOne.scala
#144 
From what I can tell, there is no need to require that ScalaTest's
`Suite` was mixed in.  Without this, this library can be used in
more contexts without dragging in scalatest classes.
This is just food for thought.  I almost never use self-types, so I
might be missing something.  However, the following appear to be true:
1. The tests of this project pass.
2. My TestNG tests that use EmbeddedKafka#start/stop work.
3. My existing Scala project that is mixing in EmbeddedKafka to
ScalaTest tests still work.
=> 144 Remove the coupling with ScalaTest

build.sbt
[Release notes](https://docs.confluent.io/4.1.1/release-notes.html#cp-4-1-1-release-notes).
=> bump Confluent version to 1.1.1

.travis.yml, build.sbt, embedded-kafka/src/main/scala/net/manub/embeddedkafka/Codecs.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/ConsumerExtensions.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/avro/avroMarshallers.scala, embedded-kafka/src/main/scala/net/manub/embeddedkafka/avro/package.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/ConsumerExtensionsSpec.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaMethodsSpec.scala, embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaObjectSpec.scala, kafka-streams/src/test/scala/net/manub/embeddedkafka/streams/ExampleKafkaStreamsSpec.scala, schema-registry/src/test/scala/net/manub/embeddedkafka/schemaregistry/EmbeddedKafkaWithSchemaRegistrySpec.scala, schema-registry/src/test/scala/net/manub/embeddedkafka/schemaregistry/streams/ExampleKafkaStreamsSchemaRegistrySpec.scala, version.sbt
`KafkaConsumer#poll(Long)` is deprecated but if I try to use `consumer.poll(Duration.ofMillis(timeout))`, it returns `null`, so I am leaving the deprecation warnings for now.
=> Kafka 2.0.0
